
ifdef DEBUG
CFLAGS		+= -g3 -ggdb3
else
CFLAGS		+= -Os
endif

CFLAGS		+= -fPIC -Wall -Wextra -Wstrict-prototypes -Wmissing-prototypes
CFLAGS		+= -Wmissing-declarations -Wshadow -Wpointer-arith
CFLAGS		+= -Wcast-qual -Wsign-compare -Wformat=2

CFLAGS		+= -Wbad-function-cast -Werror-implicit-function-declaration
CFLAGS		+= -Wfloat-equal -Wswitch-default -Wpacked
CFLAGS		+= -Wdeclaration-after-statement -Winit-self -Winline
CFLAGS		+= -Wpacked -Wlarger-than-65500 -Wunknown-pragmas
CFLAGS		+= -Wmissing-format-attribute -Wmissing-noreturn
CFLAGS		+= -Wnested-externs -Wold-style-definition -Wredundant-decls
CFLAGS		+= -Wstrict-aliasing=2 -Wswitch-enum -Wundef -Wunreachable-code
CFLAGS		+= -Wwrite-strings -Wcast-align -Wformat-nonliteral
CFLAGS		+= -Wformat-security -Waggregate-return
CFLAGS		+= -fno-common -Wp,-D_FORTIFY_SOURCE=2
CFLAGS		+= -Wmissing-field-initializers -Wmissing-include-dirs -Wunsafe-loop-optimizations
CFLAGS		+= -D_BSD_SOURCE

# vim: syntax=make
